#!/bin/sh

modprobe libcomposite
mount none /sys/kernel/config -t configfs

cd /sys/kernel/config/usb_gadget/
mkdir -p udc
cd udc

echo 0x1d6b > idVendor  # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB    # USB2

echo 0xEF > bDeviceClass
echo 0x02 > bDeviceSubClass
echo 0x01 > bDeviceProtocol

mkdir -p strings/0x409
echo "483143414d310000" > strings/0x409/serialnumber
echo "Cyrus" > strings/0x409/manufacturer
echo "Raspberry Pi Zero" > strings/0x409/product

mkdir -p configs/c.1/strings/0x409
echo "Config 1: ECM network" > configs/c.1/strings/0x409/configuration

echo 250 > configs/c.1/MaxPower

# Add functions here

# Serial
mkdir -p functions/acm.usb0
ln -s functions/acm.usb0 configs/c.1/

# Ethernet
mkdir -p functions/rndis.usb0
ln -s functions/rndis.usb0 configs/c.1/

# OS descriptors
echo 1       > os_desc/use
echo 0xcd    > os_desc/b_vendor_code
echo MSFT100 > os_desc/qw_sign

echo RNDIS   > functions/rndis.usb0/os_desc/interface.rndis/compatible_id
echo 5162001 > functions/rndis.usb0/os_desc/interface.rndis/sub_compatible_id

ln -s configs/c.1 os_desc

# Mass storage
FILE=/opt/vfat.img
mkdir -p ${FILE/img/d}
mount -o loop,rw -t vfat $FILE ${FILE/img/d}
echo "<meta HTTP-EQUIV=\"REFRESH\" content=\"0; url=http://192.168.${USB0_SUBNET}.1\">" > ${FILE/img/d}/index.html
umount ${FILE/img/d}
mount -o loop,rw -t vfat $FILE ${FILE/img/d}
mkdir -p functions/mass_storage.usb0
# echo 0 > functions/mass_storage.usb0/stall
# echo 1 > functions/mass_storage.usb0/lun.0/cdrom
# echo 1 > functions/mass_storage.usb0/lun.0/ro
# echo 0 > functions/mass_storage.usb0/lun.0/nofua
echo Y > functions/mass_storage.usb0/lun.0/removable
echo $FILE > functions/mass_storage.usb0/lun.0/file
ln -s functions/mass_storage.usb0 configs/c.1/

# End functions
ls /sys/class/udc > UDC
